version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: streamco-redis
    restart: always
    ports:
      - "7000:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --dir /data
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  redis_data: