export const MAIL_SERVICE = Symbol('MAIL_SERVICE');
export const PASSWORD_HASHER_PORT = Symbol('PASSWORD_HASHER_PORT');

export const AUTH_CACHED_USER_REPOSITORY_PORT = Symbol(
  'AUTH_CACHED_USER_REPOSITORY',
);
