export const LOG_EVENTS = {
  OTP_CREATED: 'OTP_CREATED',
  OTP_VALIDATION_FAILED: 'OTP_VALIDATION_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CREATED: 'USER_CREATED',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;
