export enum SCOPE {
  USER_READ = 'USER:READ',
  USER_WRITE = 'USER:WRITE',
  USER_DELETE = 'USER:DELETE',

  ADVERTISER_READ = 'ADVERTISER_READ',
  ADVERTISER_WRITE = 'ADVERTISER_WRITE',
  ADVERTISER_DELETE = 'ADVERTISER_DELETE',

  ADMIN_READ = 'ADMIN:READ',
  ADMIN_WRITE = 'ADMIN:WRITE',
  ADMIN_DELETE = 'ADMIN:DELETE',
}
