export const CREATE_USER_WITH_GOOGLE_AUTH_USE_CASE = Symbol(
  'CREATE_USER_WITH_GOOGLE_AUTH_USE_CASE',
);

export const GET_ALL_USERS_PORT = Symbol('GET_ALL_USERS_PORT');

export const GET_USER_BY_ID_USE_CASE = Symbol('GET_USER_BY_ID_USE_CASE');
export const UPDATE_USER_SOCIAL_LINKS_USE_CASE = Symbol(
  'UPDATE_USER_SOCIAL_LINKS_USE_CASE',
);
