export const CREATE_NORMAL_USER_USE_CASE = Symbol(
  'CREATE_NORMAL_USER_USER_CASE',
);

export const CREATE_ADVERTISER_USER_USE_CASE = Symbol(
  'CREATE_ADVERTISER_USER_USER_CASE',
);

export const CREATE_USER_WITH_GOOGLE_AUTH_USE_CASE = Symbol(
  'CREATE_USER_WITH_GOOGLE_AUTH_USE_CASE',
);
