export const CREATE_NORMAL_USER_PORT = Symbol('CREATE_NORMAL_USER_PORT');
export const CREATE_ADVERTISER_USER_PORT = Symbol(
  'CREATE_ADVERTISER_USER_PORT',
);
export const USER_REPOSITORY_PORT = Symbol('USER_REPOSITORY_PORT');
export const PASSWORD_HASHER_PORT = Symbol('PASSWORD_HASHER_PORT');
