export const CREATE_NORMAL_USER_PORT = Symbol('CREATE_NORMAL_USER_PORT');

export const USER_REPOSITORY_PORT = Symbol('USER_REPOSITORY_PORT');
export const PASSWORD_HASHER_PORT = Symbol('PASSWORD_HASHER_PORT');
export const UPDATE_USER_STATUS_PORT = Symbol('UPDATE_USER_STATUS_PORT');

export const UPDATE_USER_BASIC_PORT = Symbol('UPDATE_USER_BASIC_PORT');
export const UPDATE_USER_EMAIL_PORT = Symbol('UPDATE_USER_EMAIL_PORT');
export const CHECK_USER_EXISTS_PORT = Symbol('CHECK_USER_EXISTS_PORT');
